# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints_template.xdc

# Block Designs: bd/minlab0/minlab0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minlab0 || ORIG_REF_NAME==minlab0} -quiet] -quiet

# IP: bd/minlab0/ip/minlab0_zynq_ultra_ps_e_0_0/minlab0_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minlab0_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==minlab0_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/minlab0/ip/minlab0_rom_ctrl_0_1/minlab0_rom_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minlab0_rom_ctrl_0_1 || ORIG_REF_NAME==minlab0_rom_ctrl_0_1} -quiet] -quiet

# XDC: c:/Users/avery/ece554/minilabs/minilab0/minlab0.gen/sources_1/bd/minlab0/minlab0_ooc.xdc
