
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab1_spart(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

spart u0 (
	.clk			(CLOCK_50),
	.rst			(~KEY[0]),
	.iocs			(SW[0]),
	.iorw			(SW[1]),
	.rda			(LEDR[0]),
	.tbr			(LEDR[1]),
	.ioaddr			(SW[3:2]),
	.databus		(GPIO[7:0]),
	.txd			(GPIO[8]),
	.rxd			(GPIO[9])
);

driver u1 (
	.clk			(CLOCK_50),
	.rst			(~KEY[0]),
	.HEX0			(HEX0),
	.HEX1			(HEX1),
	.HEX2			(HEX2),
	.HEX3			(HEX3),
	.HEX4			(HEX4),
	.HEX5			(HEX5)
);


endmodule
